dist: focal

language: bash

before_script:
  - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

script: bash test/test.sh

branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
