name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  beautify:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Run beautysh
        uses: illvart/beautysh-action@latest
        with:
          # Pass beautysh options in args, for example:
          args: "*.sh --indent-size 4"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[auto] ci: apply beautysh changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Installer status with yarn
        run: bash installer.sh main yarn

      - name: Installer status with npm
        run: bash installer.sh main npm

      - name: Test the alias
        run: |
          echo "alias create-app=\"~/.config/create-app/create_app.sh\"" >> ~/.bashrc
