name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  beautify:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Run beautysh
        uses: illvart/beautysh-action@latest
        with:
          # Pass beautysh options in args, for example:
          args: "*.sh --indent-size 4"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[auto] ci: apply beautysh changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: beautify
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install shunit2
        run: curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

      - name: Run tests
        run: bash test/test.sh

  install:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installer status with yarn
        run: bash installer.sh main yarn

      - name: Installer status with npm
        run: bash installer.sh main npm

